// This file is automatically generated by Firebase Genkit.
// Do not edit this file directly.

'use server';

/**
 * @fileOverview An AI agent for analyzing call transcripts and audio metrics to assess agent behavior and provide feedback.
 *
 * - analyzeCallTranscript - A function that handles the call transcript analysis process.
 * - AnalyzeCallTranscriptInput - The input type for the analyzeCallTranscript function.
 * - AnalyzeCallTranscriptOutput - The return type for the analyzeCallTranscript function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeCallTranscriptInputSchema = z.object({
  transcript: z.string().describe('The transcript of the call.'),
  audioMetrics: z.string().describe('Audio metrics of the call, such as pauses, holds, and audio quality scores.'),
  rubricScores: z.string().describe('Scores from the rubric applied to the call.'),
});
export type AnalyzeCallTranscriptInput = z.infer<typeof AnalyzeCallTranscriptInputSchema>;

const AnalyzeCallTranscriptOutputSchema = z.object({
  agentBehaviorAssessment: z.string().describe('An assessment of the agent behavior based on the transcript and audio metrics.'),
  feedback: z.string().describe('Specific feedback for the agent, highlighting areas for improvement.'),
});
export type AnalyzeCallTranscriptOutput = z.infer<typeof AnalyzeCallTranscriptOutputSchema>;

export async function analyzeCallTranscript(input: AnalyzeCallTranscriptInput): Promise<AnalyzeCallTranscriptOutput> {
  return analyzeCallTranscriptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeCallTranscriptPrompt',
  input: {schema: AnalyzeCallTranscriptInputSchema},
  output: {schema: AnalyzeCallTranscriptOutputSchema},
  prompt: `You are an AI assistant that analyzes call transcripts, audio metrics, and rubric scores to assess agent behavior and provide targeted feedback.

  Analyze the following call transcript:
  Transcript: {{{transcript}}}

  Consider these audio metrics:
  Audio Metrics: {{{audioMetrics}}}

  Take into account the rubric scores:
  Rubric Scores: {{{rubricScores}}}

  Based on this information, assess the agent's behavior and provide specific feedback, highlighting areas for improvement. Be specific and actionable.
  Focus on areas where the agent can improve their communication skills, product knowledge, or adherence to company policies.
  Ensure feedback is constructive and addresses key aspects of the call.
  Include specific timestamps if possible to point to notable parts of the audio.

  Output your assessment and feedback in a structured format.
  `,
});

const analyzeCallTranscriptFlow = ai.defineFlow(
  {
    name: 'analyzeCallTranscriptFlow',
    inputSchema: AnalyzeCallTranscriptInputSchema,
    outputSchema: AnalyzeCallTranscriptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
